export const KEYS = {
    materials: 'materials',
    volumes: 'volumes',
    categories: 'categories',
    groups: 'groups',
    materialAds: 'materialAds',
    machinesMechanos:'mmechano',
    viewCounts:'views_count',
    works:'works',
    machinesMechanosAds:'machinesMechanosAds',
    smallMechanos:'smallmechano',
    smallMechanosAds:'smallMechanosAds',
    technos:'technos',
    technosAds:'technosAds',
};