export const URLS = {
    materials: 'materials/',
    volumes: 'volumes/',
    categories: 'categories/',
    groups: 'groups/',
    materialAds: 'materials/ads/',
    machinesMechanos: 'machines-mechanos/',
    works: 'works/',
    machinesMechanosAds: 'machines-mechanos/ads/filter/',
    smallMechanos: 'small-mechanos/',
    smallMechanosAds: 'small-mechanos/ads/filter/',
    technos: 'technos/',
    technosAds: 'materials/ads/',
    territories: 'companies/territories/',
};