export const URLS = {
    materials: 'materials/',
    volumes: 'volumes/',
    categories: 'categories/',
    groups: 'groups/',
    materialAds: 'materials/ads/',
    machinesMechanos: 'machines-mechanos/',
    works: 'works/',
    machinesMechanosAds: 'machines-mechanos/ads/',
    smallMechanos: 'small-mechanos/',
    smallMechanosAds: 'small-mechanos/ads/filter/',
    technos: 'technos/',
    technosAds: 'materials/ads/',
    territories: 'companies/territories/',
    classifierResources: 'classifier/resources/',
    classifier: 'classifier/',
    signup: 'api/register',
    getMe: 'api/user',
    login: 'api/login',
    prices: 'prices/',
    logout: 'api/logout',
};